{ config, pkgs, lib, inputs, self, ... }:

{
  # Note: inputs.worktrunk.homeModules.default intentionally NOT imported —
  # worktrunk builds from source (not in Hydra's cache) which triggers a
  # Rust compile + OOMs on constrained containers. If you want worktrunk
  # on a specific remote, build it separately and install as a package.

  # ─────────────────────────────────────────────────────────────────────
  # Basic identity — resolved from the environment at eval time so this
  # config works for any user (not just daphen). Requires --impure at
  # home-manager switch time; bootstrap.sh passes it.
  # ─────────────────────────────────────────────────────────────────────
  home.username = let
    u = builtins.getEnv "USER";
  in if u == "" then "daphen" else u;

  home.homeDirectory = let
    h = builtins.getEnv "HOME";
  in if h == "" then "/home/${config.home.username}" else h;

  home.stateVersion = "24.05";

  # ─────────────────────────────────────────────────────────────────────
  # Shell + prompt + fish-integrated tools
  # ─────────────────────────────────────────────────────────────────────
  programs.fish = {
    enable = true;
    # Note: no tokyonight-fish plugin — conf.d/fish_frozen_theme.fish (from
    # dotfiles) sets named colors; local kitty renders them with the custom
    # palette. On other terminals the colors fall back to that terminal's
    # palette — acceptable since this env is only used via SSH from local kitty.
  };

  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    # Config TOML comes from dotfiles if present; otherwise starship default.
    # User ports Tide → starship.toml manually in ~/dotfiles/starship/.config/starship.toml.
  };

  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
  };
  programs.zoxide = {
    enable = true;
    enableFishIntegration = true;
  };
  programs.git.enable = true;

  # ─────────────────────────────────────────────────────────────────────
  # Package set — the portable CLI toolkit
  # ─────────────────────────────────────────────────────────────────────
  home.packages = [
    # Bundled neovim — plugins + LSPs + lua config baked into the Nix store
    self.packages.${pkgs.system}.neovim
  ] ++ (with pkgs; [
    # AI CLIs
    claude-code
    opencode

    # CLI toolkit
    ripgrep
    fd
    bat
    jq
    gh
    delta
    fastfetch
    openssh           # ssh client (git over SSH, connecting to other hosts)

    # Auth
    _1password-cli
  ]);

  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
  };

  # Ensure ~/.local/bin is on PATH (replaces the local fish_user_paths variable
  # which doesn't port across containers).
  home.sessionPath = [ "$HOME/.local/bin" ];

  # ─────────────────────────────────────────────────────────────────────
  # Dotfile content — baked into the Nix store via inputs.dotfiles.
  # Path resolution: `inputs.dotfiles` is a fetchGit-style store path, so
  # `inputs.dotfiles + "/x/y"` composes to a concrete store path that
  # home-manager copies into place.
  # ─────────────────────────────────────────────────────────────────────
  xdg.configFile = let
    df = inputs.dotfiles;
  in {
    # Fish shell config. programs.fish.enable generates its own config.fish
    # that sources conf.d/ files automatically, so conflicts if we also set
    # config.fish — use mkForce to override with the dotfile version.
    # Intentionally not shipping fish_variables (per note in symlinks.nix).
    "fish/config.fish".source    = lib.mkForce (df + "/fish/.config/fish/config.fish");
    "fish/conf.d".source         = df + "/fish/.config/fish/conf.d";
    "fish/functions".source      = df + "/fish/.config/fish/functions";
    "fish/completions".source    = df + "/fish/.config/fish/completions";
    "fish/fish_plugins".source   = df + "/fish/.config/fish/fish_plugins";

    # Git configs
    "git/personal".source        = df + "/git/.config/git/personal";
    "git/work".source            = df + "/git/.config/git/work";
    "git/ignore".source          = df + "/git/.config/git/ignore";

    # opencode tool config + themes
    "opencode/opencode.json".source = df + "/opencode/.config/opencode/opencode.json";
    "opencode/themes".source        = df + "/opencode/.config/opencode/themes";

    # Starship prompt — generated by the theme system from starship.template,
    # applied to ~/dotfiles/starship/.config/starship/starship.toml.
    "starship.toml".source = df + "/starship/.config/starship/starship.toml";
  };

  # Home-level dotfiles
  home.file = let
    df = inputs.dotfiles;
  in {
    ".gitconfig".source         = df + "/git/.gitconfig";
    ".gitignore_global".source  = df + "/git/.gitignore_global";

    # Claude Code config — lives at ~/.claude (outside ~/.config)
    ".claude".source            = df + "/claude/.claude";
  };
}
